version: "3.8"
services:
  plearncard:
    build: "./"
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/plearncard"
      SECRET: secret
    depends_on:
      - "mongodb"
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db

volumes:
  data: